name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Check import sorting with isort
      run: |
        uv run isort --check-only --diff src tests scripts

    - name: Check code formatting with black
      run: |
        uv run black --check --diff src tests scripts

    - name: Lint with flake8
      run: |
        uv run flake8 src tests scripts --max-line-length=100 --extend-ignore=E203,W503

    - name: Type checking with mypy
      run: |
        uv run mypy src --ignore-missing-imports --strict-optional